### ISSUE TITLE
SOMETHING WENT WRONG

### ISSUE THREAD

**Issue by Expert-Hacker** [imgitto/Youtube-Video-Downloader-App#2]
If i host it on Herokuapp ,should i change **const host = "http://localhost:5000/";** to something else, because i have hosted it on heroku and am getting error **"something went wrong"** when i clicked on convert button.
Please help me ;)
Thanks in advance

**Comment by asuslaptop14321** [comment]
with me too bro please help us

**Comment by Expert-Hacker** [comment]
bro, I have resolved the issue and now website is working fine :)

checkout: https://yt-downloader-by-keerthan.herokuapp.com/

if any problem, let me know

**Comment by asuslaptop14321** [comment]
Can you please tell me which code are you changed in this script please
you can contact me too WhatsApp +4915216715756 please I am from Germany please

**Comment by asuslaptop14321** [comment]
please bro

**Comment by Expert-Hacker** [comment]
Please find my whatsapp no: click here! <https://wa.me/6361027573>

**Comment by asuslaptop14321** [comment]
hello bro I can not find your whatsapp please can you check your number please or can you whatsapp me +4915216715756 please or can you tell me which script are you changed please 🙏🙏🙏...

**Comment by asuslaptop14321** [comment]
please bro

**Comment by imgitto** [comment]
I have added fix, now its dynamically fetching hostname.
Thank you for issue report :)
